prometheus:
  service:
    type: NodePort
    nodePort: 30090
  prometheusSpec:
    retention: 7d
    resources:
      requests:
        cpu: 100m
        memory: 256Mi
      limits:
        cpu: 500m
        memory: 512Mi
    serviceMonitorSelectorNilUsesHelmValues: false
    podMonitorSelectorNilUsesHelmValues: false

grafana:
  service:
    type: NodePort
    nodePort: 30300
  adminPassword: admin
  resources:
    requests:
      cpu: 50m
      memory: 128Mi
    limits:
      cpu: 250m
      memory: 256Mi

alertmanager:
  service:
    type: NodePort
    nodePort: 30903

# kind 경량화
kubeStateMetrics:
  resources:
    requests:
      cpu: 10m
      memory: 32Mi

nodeExporter:
  resources:
    requests:
      cpu: 10m
      memory: 32Mi
